version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    groups:
      tailwindcss:
        applies-to: version-updates
        patterns:
          - "@tailwindcss*"
          - "tailwindcss*"
        update-types:
          - "major"
          - "minor"
          - "patch"
