version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      fontawesome:
        applies-to: version-updates
        patterns:
          - "@fortawesome*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      tailwindcss:
        applies-to: version-updates
        patterns:
          - "@tailwindcss*"
        update-types:
          - "major"
          - "minor"
          - "patch"
