name = "Spark"
license = "MIT"
licenselink = "https://github.com/akshaybabloo/spark-hugo-theme/blob/master/LICENSE"
description = "Dark hugo for researchers and software developers."
homepage = "https://github.com/akshaybabloo/spark-hugo-theme"
tags = ["dark theme", "research"]
features = ["google ads", "unique blog tags", "researchers specific", "custom sitemap", "direct link to external pages", "inlince CSS and JS"]
min_version = "0.51"

[author]
  name = "Akshay Raj Gollahalli"
  homepage = "https://www.gollahalli.com"
